#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/NecTouch.jar:$APPDIR/lib/core.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/SimpleOpenNI.jar:$APPDIR/lib/OpenCV.jar" NecTouch
