#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/MappiNect.jar:$APPDIR/lib/core.jar:$APPDIR/lib/SimpleOpenNI.jar:$APPDIR/lib/rwmidi.jar:$APPDIR/lib/oscP5.jar" MappiNect
